<?php
/**
 * Plugin Name: k8 Operational Intelligence
 * Plugin URI: https://kollabor8.net.au
 * Description: Embeds k8 KPI snapshots via shortcode. Supports demo and secure API modes.
 * Version: 0.1.0
 * Author: Kollabor8 Web Collectives
 * Author URI: https://kollabor8.net.au
 * License: GPLv2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: k8-operational-intel
 */

if (!defined('ABSPATH')) exit;

function k8_kpi_shortcode($atts) {

    $a = shortcode_atts(array(
        'business_id' => 'demo-tradie-001',
        'api_base' => 'http://localhost:4000',
        'mode' => 'demo' // demo or secure
    ), $atts);

    $endpoint = '';

    if ($a['mode'] === 'secure') {
        $endpoint = $a['api_base'] . '/k8-kpi/' . urlencode($a['business_id']);
        $headers = array(
            'Authorization' => 'Bearer YOUR_STATIC_DEV_TOKEN'
        );
    } else {
        $endpoint = $a['api_base'] . '/k8-demo/kpi';
        $headers = array();
    }

    $response = wp_remote_get($endpoint, array(
        'headers' => $headers,
        'timeout' => 10
    ));

    if (is_wp_error($response)) {
        return '<div class="k8-error">k8-error: API unavailable</div>';
    }

    $body = wp_remote_retrieve_body($response);
    $data = json_decode($body, true);

    if (!$data || empty($data['ok'])) {
        return '<div class="k8-error">k8-error: no data</div>';
    }

    $k = $data['data']['kpis'];

    $html  = '<div class="k8-kpi-card" style="border:1px solid #ddd;padding:20px;border-radius:12px;">';
    $html .= '<h3>Operational Snapshot (30 Days)</h3>';
    $html .= '<p><strong>Revenue:</strong> $' . number_format($k['revenue'],2) . '</p>';
    $html .= '<p><strong>Gross Margin:</strong> $' . number_format($k['gross_margin'],2) . ' (' . number_format($k['gross_margin_pct'],2) . '%)</p>';
    $html .= '<p><strong>ROAS:</strong> ' . number_format($k['roas'],2) . 'x</p>';
    $html .= '<p><strong>Leads:</strong> ' . intval($k['leads']) . '</p>';
    $html .= '</div>';

    return $html;
}

function k8oi_register_settings() {
  register_setting('k8oi_settings_group', 'k8oi_api_base');
  register_setting('k8oi_settings_group', 'k8oi_mode');
  register_setting('k8oi_settings_group', 'k8oi_jwt');
}
add_action('admin_init', 'k8oi_register_settings');

function k8oi_add_admin_menu() {
  add_options_page(
    'k8 Operational Intelligence',
    'k8 Operational Intel',
    'manage_options',
    'k8-operational-intel',
    'k8oi_settings_page'
  );
}
add_action('admin_menu', 'k8oi_add_admin_menu');

function k8oi_settings_page() {
  if (!current_user_can('manage_options')) return;

  $api_base = esc_attr(get_option('k8oi_api_base', 'http://localhost:4000'));
  $mode = esc_attr(get_option('k8oi_mode', 'demo'));
  $jwt = esc_attr(get_option('k8oi_jwt', ''));

  ?>
  <div class="wrap">
    <h1>k8 Operational Intelligence</h1>
    <p>
      Use this plugin to embed KPI snapshots generated by the k8 Operational Intelligence API.
    </p>

    <h2>Settings</h2>
    <form method="post" action="options.php">
      <?php settings_fields('k8oi_settings_group'); ?>

      <table class="form-table" role="presentation">
        <tr>
          <th scope="row"><label for="k8oi_api_base">API Base URL</label></th>
          <td><input name="k8oi_api_base" id="k8oi_api_base" type="text" class="regular-text" value="<?php echo $api_base; ?>" /></td>
        </tr>

        <tr>
          <th scope="row"><label for="k8oi_mode">Mode</label></th>
          <td>
            <select name="k8oi_mode" id="k8oi_mode">
              <option value="demo" <?php selected($mode, 'demo'); ?>>Demo (public endpoint)</option>
              <option value="secure" <?php selected($mode, 'secure'); ?>>Secure (JWT required)</option>
            </select>
          </td>
        </tr>

        <tr>
          <th scope="row"><label for="k8oi_jwt">JWT (Secure Mode Only)</label></th>
          <td>
            <input name="k8oi_jwt" id="k8oi_jwt" type="text" class="regular-text" value="<?php echo $jwt; ?>" />
            <p class="description">Store a token here for secure KPI reads. Do not paste tokens into shortcodes.</p>
          </td>
        </tr>
      </table>

      <?php submit_button(); ?>
    </form>

    <hr />

    <h2>Shortcode</h2>
    <p><code>[k8_kpi business_id="demo-tradie-001"]</code></p>

    <h3>Attributes</h3>
    <ul>
      <li><strong>business_id</strong> (string) — required for secure mode; ignored for demo mode.</li>
    </ul>

    <h2>Accessibility Notes</h2>
    <p>
      KPI output is rendered as semantic HTML with readable text. If you add custom styling, ensure sufficient color contrast
      and preserve heading hierarchy.
    </p>

    <h2>Support</h2>
    <p>
      Built by Kollabor8 Web Collectives. For support, refer to your internal delivery notes or contact your administrator.
    </p>
  </div>
  <?php
}

add_shortcode('k8_kpi', 'k8_kpi_shortcode');
